"""empty message

Revision ID: 4a7f244429f1
Revises: f00f21649613
Create Date: 2020-06-16 22:30:24.487017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a7f244429f1'
down_revision = 'f00f21649613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_gallery_title'), 'gallery', ['title'], unique=False)
    op.drop_index('ix_gallery_image', table_name='gallery')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_gallery_image', 'gallery', ['image'], unique=False)
    op.drop_index(op.f('ix_gallery_title'), table_name='gallery')
    # ### end Alembic commands ###
