"""empty message

Revision ID: f00f21649613
Revises: d40009ef783c
Create Date: 2020-06-16 22:28:47.522683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00f21649613'
down_revision = 'd40009ef783c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('image', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_image'), 'gallery', ['image'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gallery_image'), table_name='gallery')
    op.drop_table('gallery')
    # ### end Alembic commands ###
